// Date: 16/05/2013 23:07:05
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mymod.renders.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class DrainModel extends ModelBase
{
  //fields
    ModelRenderer Middel;
    ModelRenderer Right;
    ModelRenderer Left;
  
    public DrainModel() {
      
        textureWidth = 128;
        textureHeight = 32;
         
        Left = new ModelRenderer(this, 40, 0);
        Left.mirror = true;
        Left.addBox(0F, 0F, 0F, 6, 16, 16);
        Left.setRotationPoint(-6F, -16F, 0F);
        Left.setTextureSize(128, 32);
        Left.mirror = true;
        setRotation(Left, 0F, 0F, 0F);
        Left.mirror = false;
        Middel = new ModelRenderer(this, 0, 0);
        Middel.addBox(0F, 0F, 0F, 4, 12, 16);
        Middel.setRotationPoint(-10F, -12F, 0F);
        Middel.setTextureSize(128, 32);
        Middel.mirror = true;
        setRotation(Middel, 0F, 0F, 0F);
        Right = new ModelRenderer(this, 40, 0);
        Right.mirror = true;
        Right.addBox(0F, 0F, 0F, 6, 16, 16);
        Right.setRotationPoint(-16F, -16F, 0F);
        Right.setTextureSize(128, 32);
        Right.mirror = true;
        setRotation(Right, 0F, 0F, 0F);
        Right.mirror = false;
      
      }
        
        public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
        {
          super.render(entity, f, f1, f2, f3, f4, f5);
          setRotationAngles(f, f1, f2, f3, f4, f5, entity);
          Left.render(f5);
          Middel.render(f5);
          Right.render(f5);
        }
        
        private void setRotation(ModelRenderer model, float x, float y, float z)
        {
          model.rotateAngleX = x;
          model.rotateAngleY = y;
          model.rotateAngleZ = z;
        }
    
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
      super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

  }
