// Date: 15/05/2013 13:52:09
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modeltable extends ModelBase
{
  //fields
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Top;
    ModelRenderer Edge1;
    ModelRenderer Edge2;
    ModelRenderer Edge3;
    ModelRenderer Edge4;
    ModelRenderer Spanner1;
    ModelRenderer Spanner2;
    ModelRenderer Spanner3;
    ModelRenderer Spanner4;
  
  public Modeltable()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Leg1 = new ModelRenderer(this, 0, 18);
      Leg1.addBox(0F, 0F, 0F, 2, 16, 2);
      Leg1.setRotationPoint(-8F, 8F, -8F);
      Leg1.setTextureSize(128, 64);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 0, 18);
      Leg2.addBox(0F, 0F, 0F, 2, 16, 2);
      Leg2.setRotationPoint(6F, 8F, -8F);
      Leg2.setTextureSize(128, 64);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 0, 18);
      Leg3.addBox(0F, 0F, 0F, 2, 16, 2);
      Leg3.setRotationPoint(-8F, 8F, 6F);
      Leg3.setTextureSize(128, 64);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 0, 18);
      Leg4.addBox(0F, 0F, 0F, 2, 16, 2);
      Leg4.setRotationPoint(6F, 8F, 6F);
      Leg4.setTextureSize(128, 64);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 0, 0);
      Top.addBox(0F, 0F, 0F, 16, 2, 16);
      Top.setRotationPoint(-8F, 8F, -8F);
      Top.setTextureSize(128, 64);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      Edge1 = new ModelRenderer(this, 8, 34);
      Edge1.addBox(0F, 0F, 0F, 16, 1, 1);
      Edge1.setRotationPoint(-8F, 10F, -8F);
      Edge1.setTextureSize(128, 64);
      Edge1.mirror = true;
      setRotation(Edge1, 0F, 0F, 0F);
      Edge2 = new ModelRenderer(this, 8, 34);
      Edge2.addBox(0F, 0F, 0F, 16, 1, 1);
      Edge2.setRotationPoint(-8F, 10F, 7F);
      Edge2.setTextureSize(128, 64);
      Edge2.mirror = true;
      setRotation(Edge2, 0F, 0F, 0F);
      Edge3 = new ModelRenderer(this, 8, 19);
      Edge3.addBox(0F, 0F, 0F, 1, 1, 16);
      Edge3.setRotationPoint(-8F, 10F, -8F);
      Edge3.setTextureSize(128, 64);
      Edge3.mirror = true;
      setRotation(Edge3, 0F, 0F, 0F);
      Edge4 = new ModelRenderer(this, 8, 18);
      Edge4.addBox(0F, 0F, 0F, 1, 1, 16);
      Edge4.setRotationPoint(7F, 10F, -8F);
      Edge4.setTextureSize(128, 64);
      Edge4.mirror = true;
      setRotation(Edge4, 0F, 0F, 0F);
      Spanner1 = new ModelRenderer(this, 8, 19);
      Spanner1.addBox(0F, 0F, 0F, 1, 1, 16);
      Spanner1.setRotationPoint(-8F, 12F, -8F);
      Spanner1.setTextureSize(128, 64);
      Spanner1.mirror = true;
      setRotation(Spanner1, 0.0174533F, 0F, 0F);
      Spanner2 = new ModelRenderer(this, 8, 19);
      Spanner2.addBox(0F, 0F, 0F, 1, 1, 16);
      Spanner2.setRotationPoint(7F, 12F, -8F);
      Spanner2.setTextureSize(128, 64);
      Spanner2.mirror = true;
      setRotation(Spanner2, 0F, 0F, 0F);
      Spanner3 = new ModelRenderer(this, 8, 34);
      Spanner3.addBox(0F, 0F, 0F, 16, 1, 1);
      Spanner3.setRotationPoint(-8F, 12F, 7F);
      Spanner3.setTextureSize(128, 64);
      Spanner3.mirror = true;
      setRotation(Spanner3, 0F, 0F, 0F);
      Spanner4 = new ModelRenderer(this, 8, 34);
      Spanner4.addBox(0F, 0F, 0F, 16, 1, 1);
      Spanner4.setRotationPoint(-8F, 12F, -8F);
      Spanner4.setTextureSize(128, 64);
      Spanner4.mirror = true;
      setRotation(Spanner4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Leg1.render(f5);
    Leg2.render(f5);
    Leg3.render(f5);
    Leg4.render(f5);
    Top.render(f5);
    Edge1.render(f5);
    Edge2.render(f5);
    Edge3.render(f5);
    Edge4.render(f5);
    Spanner1.render(f5);
    Spanner2.render(f5);
    Spanner3.render(f5);
    Spanner4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
